### ISSUE TITLE
Konferencje w 2020

### ISSUE THREAD

**Issue by zaza** [cezarypiatek/polish-it-conferences#20]
Jest już druga połowa 2019 więc może warto zacząc dodawać wydarzenia w nadchodzącym 2020 roku?

Dla poprawienia czytelności usunałbym też historyczne wpisy dla 2018 i wcześniejsze. Albo przeniósł do brancha?

Co wy na to?

**Comment by cezarypiatek** [comment]
Cześć @zaza 

Dzięki za poruszenie tematu. Od jakiegoś czasu zastanawiam się nad tym aby podzielić listę na osobne pliki względem roku konferencjinego a w głównym readme dać tylko linki do konkretnych plików. Co ty o tym sądzisz?

Jeśli chodzi o rok 2020 to jeszcze nie trafiłem aby ktoś ogłosił już konkretny termin którejkolwiek konferencji na 2020 ale istnieje wysokie ryzyko iż mogłem coś przeoczyć. Jeśli masz już jakieś konkrene info to postaram się od razu po ustaleniu nowej formy zrobić miejsce na 2020.

**Comment by zaza** [comment]
> (...) podzielić listę na osobne pliki względem roku konferencjinego a w głównym readme dać tylko linki do konkretnych plików.

Brzmi lepiej niż branche.

> (...) konkretny termin którejkolwiek konferencji na 2020 (...)

Fakt, ale ja muszę z wyprzedzeniem planować na które chciałbym pojechać. Dokładny termin jest drugorzędny. No chyba, że są tego samego dnia :)

**Comment by cezarypiatek** [comment]
Ok, porządek zrobiony oraz lista na 2020 założona.
