### ISSUE TITLE
Dodać kolumnę z informacją czy konferencja oferuje warsztaty

### ISSUE THREAD

**Issue by cezarypiatek** [cezarypiatek/polish-it-conferences#22]
Nowe zmiany od 2020

**Comment by P1X3L0V4** [comment]
Witam. Chętnie zajmę się realizacją tego taska. Prośba o info zwrotne czy są jakieś dodatkowe wytyczne? Np. Czy kolumna ma być jako ostatnia w kolejności?

**Comment by cezarypiatek** [comment]
Może być jako ostatnia kolumna. Dzięki bardzo. PR zmergowany.
