### ISSUE TITLE
Pilik kalendarza się nie aktualizuje po dodaniu zmian do plików md

### ISSUE THREAD

**Issue by cezarypiatek** [cezarypiatek/polish-it-conferences#41]
Zauważyłęm, że aktualnie brakuje już kilku wydarzeń z 2020 - np Boiling Frogs.

@mlebkowski czy możesz na to zerknąć?

**Comment by mlebkowski** [comment]
Teraz jest ok? Zmiany powinny wchodzić raz dziennie w nocy

**Comment by cezarypiatek** [comment]
W tym momencie plik wygląda ok natomiast zawartość kalendarza w outlook się nie odświeżyła. Podejrzewam iż jest to spowodowane tym, że plik kalendarza jest serwowany po protokole `https://` a nie `webcal://`. Prośba o weryfikację.

**Comment by mlebkowski** [comment]
[🤷‍♀️](https://stackoverflow.com/a/5603900)

**Comment by cezarypiatek** [comment]
Nie do końca rozumiem ten opis. Czy kalendarz będzie mi się automatycznie aktualizował czy musze go codziennie na nowo importować aby mieć aktualne dane?

**Comment by cezarypiatek** [comment]
Ok, dzisiaj zauważyłęm że jednak kalendarz się aktualizuje, ale z dużym opóźnieniem
