### ISSUE TITLE
Dodać kolumnę z labelkami kategoryzującymi dane wydarzenie

### ISSUE THREAD

**Issue by cezarypiatek** [cezarypiatek/polish-it-conferences#6]
Przydałaby się kolumna z labelkami
- .net
- java
- frontend
- mobile
- testing
- craftsmanship
- security
- cloud
- etc.

**Comment by pawlos** [comment]
ciekawy pomysł, choć przy niektórych konferencjach może wyjść z tego niezła litania labelek ;)

**Comment by cezarypiatek** [comment]
No właśnie pytanie jak klasyfikować konferencje typu `4Developers` gdzie jest 15 ścieżek pokrywających właściwie wszystko co się da w IT. Kolejną zagadką są eventy typu `Kariera IT` czy też `InfoMEET`.

**Comment by cezarypiatek** [comment]
Hej @pawlos Zrobiłem wstępną klasyfikachę w ramach #8, mógłbyś rzucić na to okiem? Każda uwaga mile widziana. Dla tych "interdyscyplinarnych" użyłem labelki `versatile`. (Labelki po angielsku, jakoś to bardzie zwięźle wygląda)

**Comment by pawlos** [comment]
@cezarypiatek dzięki. 

Zerknąłem na listę i to moje uwagi (których możesz nie brać pod uwagę ;)):

Jak dla mnie to ten tag "Versatile" nic nie mówi. Wciąż nie wiem czego się spodziewać po takiej konferencji i czy chciałbym się na nią wybrać. Choć nie twierdzę, że nic ten tag nie mówi np. bardzo się zdziwiłem czytając, że pyrcode taki miał bo myślałem, że to konfa o pythonie ;) 

Z drugiej strony taki Devoxx ma java + versatile co trochę z definicji się kłóci ze sobą. SQLDay bardziej bym opisał jako database niż data, bo to ostatnie bardziej dla mnie kojarzy się z jakimś big data czy machine learningiem itp.

Niektóre konferencje oferują warsztaty - może warto to uwzględnić?

**Comment by cezarypiatek** [comment]
Dzięki za uwagi. W kolejnej "iteracji" spróbuję doszczegółowić to versatile.  Swoją droga świetny pomysł z uwzględnieniem tych warsztatów.
